# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@chromatic-com/storybook"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@stencil/sass"
        versions: [">=3.0.13"]
      - dependency-name: storybook
        update-types: ["version-update:semver-major"]
      - dependency-name: "@storybook/addon-actions"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@storybook/addon-essentials"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@storybook/addon-interactions"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@storybook/addon-links"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@storybook/html"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@storybook/html-webpack5"
        update-types: ["version-update:semver-major"]
    groups:
      all-dependencies:
        patterns:
          - "*"
