version: 2.1

orbs:
  docker: circleci/docker@2.1.2
  jira: circleci/jira@1.3.1

defaults: &defaults
  working_directory: ~/components
  docker:
    - image: thebiggive/donate-frontend-ci:latest
      auth:
        username: $DOCKER_HUB_USERNAME
        password: $DOCKER_HUB_ACCESS_TOKEN

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install --quiet
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run lint
      - run: npm run test

  # Publishes `@biggive/components` *and* `@biggive/components-angular` (building both on the fly).
  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install --quiet
      - run: cd angular && npm install --quiet && cd ..
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_AUTH_TOKEN" > ~/components/.npmrc
      - run:
          name: Publish core components to npm
          command: npm publish --access=public
      - run:
          name: Install Angular CLI
          command: npm install -g @angular/cli@latest
      - run:
          name: Build Angular components
          command: cd angular && npm run build
      - run:
          name: Authenticate with registry in Angular components output directory
          command: echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_AUTH_TOKEN" > ~/components/angular/dist/components/.npmrc
      - run:
          name: Publish Angular components to npm
          command: cd angular/dist/components && npm publish --access=public

workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - docker-hub-creds
            - jira
          post-steps:
            - jira/notify:
                job_type: build
                environment_type: development
  publish:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - main
            tags:
              only: /^v.*/
          context:
            - docker-hub-creds
            - jira
            - npm-publish
          post-steps:
            - jira/notify:
                job_type: deployment
                environment_type: production
